// Generated by https://quicktype.io

class Localidades {
  List<Localidad> items = List();

  Localidades();

  Localidades.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    for (var item in jsonList) {
      Localidad localidad = Localidad.fromJsonMap(item);
      items.add(localidad);
    }
  }
  
}

class Localidad {
  int id;
  String nombre;

  Localidad({
    this.id,
    this.nombre,
  });

  Localidad.fromJsonMap(Map<String, dynamic> json) {
    this.id     = json["id"];
    this.nombre = json["nombre"];
  }
}
